name: "posts-api"

services:
  apigateway:
    container_name: apigateway
    build:
      context: ./ApiGateway
    ports:
      - 8081:8080
  userservice:
    container_name: userservice
    build:
      context: ./
      dockerfile: ./UserService/Dockerfile
    ports:
      - 8082:8080
    networks:
      - postgres-network
      - rabbitmq-network
    depends_on:
      usersdb:
        condition: service_started
      rabbitmq:
        condition: service_started
  usersdb:
    container_name: usersdb
    hostname: usersdb
    image: "postgres:alpine3.19"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    networks:
      - postgres-network
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.9-management
    expose:
      - 5672
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - rabbitmq-network
networks:
  postgres-network:
    driver: bridge
  rabbitmq-network:
    driver: bridge
